-- ============================================================================
-- ADL Migration 061: CIFP Import Stored Procedure
--
-- Creates sp_ImportCIFPProcedures for bulk importing CIFP procedure data
-- from CSV files generated by Import-CIFPProcedures.ps1
--
-- Usage:
--   EXEC sp_ImportCIFPProcedures
--     @procedures_csv = 'C:\path\to\cifp_procedures.csv',
--     @legs_csv = 'C:\path\to\cifp_legs.csv'
-- ============================================================================

SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

PRINT '=== ADL Migration 061: CIFP Import Procedure ===';
PRINT 'Started at: ' + CONVERT(VARCHAR, GETUTCDATE(), 120);
GO

-- ============================================================================
-- Create Import Stored Procedure
-- ============================================================================

IF OBJECT_ID('dbo.sp_ImportCIFPProcedures', 'P') IS NOT NULL
    DROP PROCEDURE dbo.sp_ImportCIFPProcedures;
GO

CREATE PROCEDURE dbo.sp_ImportCIFPProcedures
    @procedures_csv NVARCHAR(500),
    @legs_csv       NVARCHAR(500),
    @clear_existing BIT = 0,
    @debug          BIT = 0
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @start_time DATETIME2 = SYSUTCDATETIME();
    DECLARE @proc_count INT = 0;
    DECLARE @legs_count INT = 0;
    DECLARE @new_procs INT = 0;
    DECLARE @updated_procs INT = 0;
    DECLARE @new_legs INT = 0;

    PRINT '================================================';
    PRINT 'CIFP Procedure Import';
    PRINT 'Started at: ' + CONVERT(VARCHAR, @start_time, 120);
    PRINT '================================================';

    -- ========================================================================
    -- Clear existing CIFP data if requested
    -- ========================================================================
    IF @clear_existing = 1
    BEGIN
        PRINT '';
        PRINT 'Clearing existing CIFP data...';

        -- Delete legs first (FK constraint)
        DELETE FROM dbo.nav_procedure_legs
        WHERE procedure_id IN (
            SELECT procedure_id FROM dbo.nav_procedures WHERE cifp_file IS NOT NULL
        );
        PRINT '  Deleted existing CIFP procedure legs';

        -- Reset has_leg_detail flag
        UPDATE dbo.nav_procedures
        SET has_leg_detail = 0,
            cifp_file = NULL,
            cifp_import_utc = NULL
        WHERE cifp_file IS NOT NULL;
        PRINT '  Reset CIFP flags on existing procedures';
    END

    -- ========================================================================
    -- Import Procedures CSV to staging
    -- ========================================================================
    PRINT '';
    PRINT 'Importing procedures from: ' + @procedures_csv;

    TRUNCATE TABLE dbo.cifp_procedures_staging;

    DECLARE @bulk_sql NVARCHAR(MAX) = N'
        BULK INSERT dbo.cifp_procedures_staging
        FROM ''' + @procedures_csv + '''
        WITH (
            FORMAT = ''CSV'',
            FIRSTROW = 2,
            FIELDTERMINATOR = '','',
            ROWTERMINATOR = ''\n'',
            TABLOCK,
            CODEPAGE = ''65001''
        )';

    BEGIN TRY
        EXEC sp_executesql @bulk_sql;

        SELECT @proc_count = COUNT(*) FROM dbo.cifp_procedures_staging;
        PRINT '  Loaded ' + CAST(@proc_count AS VARCHAR) + ' procedures to staging';
    END TRY
    BEGIN CATCH
        PRINT '  ERROR loading procedures: ' + ERROR_MESSAGE();
        RETURN -1;
    END CATCH

    -- ========================================================================
    -- Import Legs CSV to staging
    -- ========================================================================
    PRINT '';
    PRINT 'Importing legs from: ' + @legs_csv;

    TRUNCATE TABLE dbo.cifp_legs_staging;

    SET @bulk_sql = N'
        BULK INSERT dbo.cifp_legs_staging
        FROM ''' + @legs_csv + '''
        WITH (
            FORMAT = ''CSV'',
            FIRSTROW = 2,
            FIELDTERMINATOR = '','',
            ROWTERMINATOR = ''\n'',
            TABLOCK,
            CODEPAGE = ''65001''
        )';

    BEGIN TRY
        EXEC sp_executesql @bulk_sql;

        SELECT @legs_count = COUNT(*) FROM dbo.cifp_legs_staging;
        PRINT '  Loaded ' + CAST(@legs_count AS VARCHAR) + ' legs to staging';
    END TRY
    BEGIN CATCH
        PRINT '  ERROR loading legs: ' + ERROR_MESSAGE();
        RETURN -1;
    END CATCH

    -- ========================================================================
    -- MERGE procedures into nav_procedures
    -- Match on airport_icao + procedure_name + procedure_type
    -- ========================================================================
    PRINT '';
    PRINT 'Merging procedures into nav_procedures...';

    -- First, update existing procedures
    UPDATE np
    SET np.has_leg_detail = 1,
        np.cifp_file = s.cifp_file,
        np.cifp_import_utc = GETUTCDATE(),
        np.transition_name = COALESCE(np.transition_name, s.runway_transition),
        np.runways = COALESCE(np.runways,
            CASE WHEN s.runway_transition LIKE 'RW%' THEN SUBSTRING(s.runway_transition, 3, 10) ELSE NULL END)
    FROM dbo.nav_procedures np
    INNER JOIN (
        SELECT DISTINCT
            airport_icao,
            procedure_type,
            procedure_name,
            runway_transition,
            cifp_file
        FROM dbo.cifp_procedures_staging
    ) s ON np.airport_icao = s.airport_icao
       AND np.procedure_name = s.procedure_name
       AND np.procedure_type = s.procedure_type;

    SET @updated_procs = @@ROWCOUNT;
    PRINT '  Updated ' + CAST(@updated_procs AS VARCHAR) + ' existing procedures';

    -- Insert new procedures (not already in nav_procedures)
    INSERT INTO dbo.nav_procedures (
        procedure_type,
        airport_icao,
        procedure_name,
        computer_code,
        transition_name,
        runways,
        is_active,
        source,
        has_leg_detail,
        cifp_file,
        cifp_import_utc
    )
    SELECT DISTINCT
        s.procedure_type,
        s.airport_icao,
        s.procedure_name,
        -- Generate computer_code: NAME.TRANSITION or just NAME
        CASE
            WHEN s.runway_transition IS NOT NULL AND s.runway_transition != '' AND s.runway_transition != 'ALL'
            THEN s.procedure_name + '.' + s.runway_transition
            ELSE s.procedure_name
        END,
        s.runway_transition,
        CASE WHEN s.runway_transition LIKE 'RW%' THEN SUBSTRING(s.runway_transition, 3, 10) ELSE NULL END,
        1,  -- is_active
        'CIFP',
        1,  -- has_leg_detail
        s.cifp_file,
        GETUTCDATE()
    FROM dbo.cifp_procedures_staging s
    WHERE NOT EXISTS (
        SELECT 1 FROM dbo.nav_procedures np
        WHERE np.airport_icao = s.airport_icao
          AND np.procedure_name = s.procedure_name
          AND np.procedure_type = s.procedure_type
    );

    SET @new_procs = @@ROWCOUNT;
    PRINT '  Inserted ' + CAST(@new_procs AS VARCHAR) + ' new procedures';

    -- ========================================================================
    -- Insert procedure legs
    -- ========================================================================
    PRINT '';
    PRINT 'Inserting procedure legs...';

    -- Delete existing legs for procedures we're updating
    DELETE pl
    FROM dbo.nav_procedure_legs pl
    INNER JOIN dbo.nav_procedures np ON pl.procedure_id = np.procedure_id
    WHERE np.cifp_import_utc >= DATEADD(MINUTE, -5, GETUTCDATE());

    PRINT '  Cleared existing legs for updated procedures';

    -- Insert new legs
    INSERT INTO dbo.nav_procedure_legs (
        procedure_id,
        sequence_num,
        route_type,
        fix_name,
        fix_region,
        fix_section,
        leg_type,
        outbound_course,
        inbound_course,
        distance_nm,
        rec_navaid,
        rec_navaid_region,
        alt_restriction,
        altitude_1_ft,
        altitude_2_ft,
        speed_limit_kts,
        speed_restriction,
        is_flyover,
        is_hold_waypoint
    )
    SELECT
        np.procedure_id,
        s.sequence_num,
        s.route_type,
        NULLIF(s.fix_name, ''),
        NULLIF(s.fix_region, ''),
        NULLIF(s.fix_section, ''),
        s.leg_type,
        s.outbound_course,
        s.inbound_course,
        s.distance_nm,
        NULLIF(s.rec_navaid, ''),
        NULLIF(s.rec_navaid_region, ''),
        NULLIF(s.alt_restriction, ''),
        s.altitude_1_ft,
        s.altitude_2_ft,
        s.speed_limit_kts,
        NULLIF(s.speed_restriction, ''),
        s.is_flyover,
        s.is_hold_waypoint
    FROM dbo.cifp_legs_staging s
    INNER JOIN dbo.nav_procedures np
        ON np.airport_icao = s.airport_icao
       AND np.procedure_name = s.procedure_name
       AND np.procedure_type = s.procedure_type
    WHERE np.has_leg_detail = 1;

    SET @new_legs = @@ROWCOUNT;
    PRINT '  Inserted ' + CAST(@new_legs AS VARCHAR) + ' procedure legs';

    -- ========================================================================
    -- Build full_route from legs for new procedures
    -- ========================================================================
    PRINT '';
    PRINT 'Building full_route strings from legs...';

    ;WITH route_fixes AS (
        SELECT
            procedure_id,
            STRING_AGG(fix_name, ' ') WITHIN GROUP (ORDER BY sequence_num) AS fix_sequence
        FROM dbo.nav_procedure_legs
        WHERE fix_name IS NOT NULL
        GROUP BY procedure_id
    )
    UPDATE np
    SET np.full_route = rf.fix_sequence
    FROM dbo.nav_procedures np
    INNER JOIN route_fixes rf ON np.procedure_id = rf.procedure_id
    WHERE np.source = 'CIFP'
      AND (np.full_route IS NULL OR np.full_route = '');

    PRINT '  Updated full_route for CIFP procedures';

    -- ========================================================================
    -- Summary
    -- ========================================================================
    DECLARE @elapsed_sec INT = DATEDIFF(SECOND, @start_time, SYSUTCDATETIME());

    PRINT '';
    PRINT '================================================';
    PRINT 'Import Complete';
    PRINT '================================================';
    PRINT '  Procedures updated: ' + CAST(@updated_procs AS VARCHAR);
    PRINT '  Procedures inserted: ' + CAST(@new_procs AS VARCHAR);
    PRINT '  Legs inserted: ' + CAST(@new_legs AS VARCHAR);
    PRINT '  Elapsed time: ' + CAST(@elapsed_sec AS VARCHAR) + ' seconds';
    PRINT '';

    -- Return summary as result set
    SELECT
        @updated_procs AS procedures_updated,
        @new_procs AS procedures_inserted,
        @new_legs AS legs_inserted,
        @elapsed_sec AS elapsed_seconds;
END
GO

PRINT 'Created procedure: sp_ImportCIFPProcedures';
GO

-- ============================================================================
-- Complete
-- ============================================================================

PRINT '';
PRINT '=== Migration 061 Complete ===';
PRINT 'Completed at: ' + CONVERT(VARCHAR, GETUTCDATE(), 120);
PRINT '';
PRINT 'Stored procedures created:';
PRINT '  - sp_ImportCIFPProcedures (bulk import from CSV)';
PRINT '';
PRINT 'Usage:';
PRINT '  1. Run Import-CIFPProcedures.ps1 to generate CSV files';
PRINT '  2. Execute:';
PRINT '     EXEC sp_ImportCIFPProcedures';
PRINT '       @procedures_csv = ''C:\path\to\cifp_procedures.csv'',';
PRINT '       @legs_csv = ''C:\path\to\cifp_legs.csv''';
GO
