<?php
/**
 * ATC-Zero Avoidance Route Import
 *
 * Imports ATC-Zero contingency avoidance routes from the vATCSCC ATC-Zero
 * Avoidance Package (11 August 2020) into the playbook system. 21 plays
 * with 543 routes covering ATC-Zero avoidance scenarios for US ARTCCs.
 *
 * Source: vATCSCC ATC-Zero Avoidance Package (Google Slides, 87 slides)
 * Category: Contingency
 * Source: DCC, org_code: ATC_ZERO
 *
 * Idempotent: deletes existing ATC_ZERO plays before re-importing.
 * Skips routes that already exist in other Contingency plays (user-added).
 * Uses batch INSERT for performance.
 *
 * Usage: Upload to Azure via VFS API, hit via public URL, then delete.
 */

set_time_limit(120);
header('Content-Type: text/plain; charset=utf-8');

$host = "vatcscc-perti.mysql.database.azure.com";
$db   = "perti_site";
$user = "jpeterson";
$pass = "Jhp21012";

try {
    $pdo = new PDO("mysql:host=$host;dbname=$db;charset=utf8mb4", $user, $pass, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false,
    ]);
} catch (PDOException $e) {
    die("DB connection failed: " . $e->getMessage() . "\n");
}

function normPlay($n) { return strtoupper(preg_replace('/[^A-Z0-9]/i', '', $n)); }

/**
 * Parse origin/destination from route string.
 * First token: K-prefix = airport, Z-prefix/CZY/N90 = ARTCC, UNKN = various
 * Last token: same logic
 */
function parseOriginDest($route_str) {
    $tokens = preg_split('/\s+/', trim($route_str));
    $first = $tokens[0];
    $last = end($tokens);

    $orig_apt = ''; $orig_artcc = '';
    $dest_apt = ''; $dest_artcc = '';

    if (preg_match('/^K[A-Z]{3}$/', $first)) {
        $orig_apt = $first;
    } elseif (preg_match('/^(Z[A-Z]{2}|CZ[A-Z]|N90)$/', $first)) {
        $orig_artcc = $first;
    }

    if (preg_match('/^K[A-Z]{3}$/', $last)) {
        $dest_apt = $last;
    } elseif (preg_match('/^(Z[A-Z]{2}|CZ[A-Z]|N90)$/', $last)) {
        $dest_artcc = $last;
    }

    $origin = $orig_apt ?: ($orig_artcc ?: ($first === 'UNKN' ? 'VARIOUS' : $first));
    $dest   = $dest_apt ?: ($dest_artcc ?: ($last === 'UNKN' ? 'VARIOUS' : $last));

    return [$origin, $dest, $orig_apt, $orig_artcc, $dest_apt, $dest_artcc];
}

// ============================================================================
// PLAY DEFINITIONS
// ============================================================================
$plays = [
    'ZAB ATC-0 MEX' => [
        'display_name' => 'ATC-Zero ZAB - Mexico Avoidance (FCA005)',
        'description' => 'ATC-Zero avoidance routes through Mexican airspace when ZAB is ATC-Zero. MXL-THX-CEW corridor provides routing for ZOA/ZLA origins to KHOU/KIAH and NE corridor airports via ZHU/ZFW.',
        'impacted_area' => 'ZAB',
        'facilities_involved' => 'ZAB,ZOA,ZLA,ZHU,ZFW,ZME,ZID,ZDC,ZNY',
    ],
    'ZDC ATC-0 FCA003' => [
        'display_name' => 'ATC-Zero ZDC - Tower Enroute (FCA003)',
        'description' => 'Tower enroute routes when ZDC is ATC-Zero. Routes from FL/SE/SW/Central origins via connect fixes SPA, APE, ROD, JOT to NE corridor destinations (KBWI, KDCA, KIAD, KEWR, KJFK, KLGA, KPHL, KTEB).',
        'impacted_area' => 'ZDC',
        'facilities_involved' => 'ZDC,ZTL,ZJX,ZMA,ZID,ZME,ZFW,ZHU,ZKC,ZOB',
    ],
    'ZDC ATC-0 FCA002' => [
        'display_name' => 'ATC-Zero ZDC - V-Routes (FCA002)',
        'description' => 'Tower enroute V-routes when ZDC is ATC-Zero. Routes from ZTL/ZMA/ZJX via PSK V16 ROA V375 CLYFF CSN to KIAD, KBWI, KDCA.',
        'impacted_area' => 'ZDC',
        'facilities_involved' => 'ZDC,ZTL,ZMA,ZJX',
    ],
    'ZDV ATC-0' => [
        'display_name' => 'ATC-Zero ZDV - Avoidance Segments (FCA011)',
        'description' => 'ATC-Zero avoidance segments when ZDV is ATC-Zero. Four bypass corridors: south (PGS-ICT), north (ABR-DBS), west (PGS-BOY), east (RWF-ICT).',
        'impacted_area' => 'ZDV',
        'facilities_involved' => 'ZDV,ZAB,ZKC,ZMP,ZLC,ZSE',
    ],
    'ZFW ATC-0' => [
        'display_name' => 'ATC-Zero ZFW - Routes',
        'description' => 'ATC-Zero routes when ZFW is ATC-Zero. MARTA arrival route to KSHV.',
        'impacted_area' => 'ZFW',
        'facilities_involved' => 'ZFW,ZME',
    ],
    'ZHU ATC-0 DEP' => [
        'display_name' => 'ATC-Zero ZHU - Departure Routes (FCA003)',
        'description' => 'Departure routes when ZHU is ATC-Zero. KIAH/KHOU departures routed to KDFW/KDAL via IAH CRIED corridor, plus westbound exits via LOA/SAT/ABI.',
        'impacted_area' => 'ZHU',
        'facilities_involved' => 'ZHU,ZFW,ZAB',
    ],
    'ZHU ATC-0 ARR' => [
        'display_name' => 'ATC-Zero ZHU - Arrival Routes (FCA004)',
        'description' => 'Arrival routes when ZHU is ATC-Zero. Arrivals to KIAH/KHOU via CVE RIICE corridor, KSAT/KAUS arrivals via ACT/WINDU.',
        'impacted_area' => 'ZHU',
        'facilities_involved' => 'ZHU,ZFW,ZAB,ZME',
    ],
    'ZHO ATC-0 GULF EB' => [
        'display_name' => 'ATC-Zero ZHO/Gulf - Eastbound (FCA002)',
        'description' => 'Eastbound Gulf crossing routes when ZHU Offshore (ZHO) is ATC-Zero. Routes via LAMMY/IAH KENGS to ZMA/KMCO using REMIS or BACCA transitions.',
        'impacted_area' => 'ZHU',
        'facilities_involved' => 'ZHU,ZFW,ZMA',
    ],
    'ZHO ATC-0 GULF WB' => [
        'display_name' => 'ATC-Zero ZHO/Gulf - Westbound (FCA001)',
        'description' => 'Westbound Gulf crossing routes when ZHU Offshore (ZHO) is ATC-Zero. Routes from ZMA/KMCO via KENGS IAH to KDFW/KDAL using REMIS or BACCA transitions.',
        'impacted_area' => 'ZHU',
        'facilities_involved' => 'ZHU,ZFW,ZMA',
    ],
    'ZID ATC-0 CVG' => [
        'display_name' => 'ATC-Zero ZID - CVG Routes (FCA010)',
        'description' => 'ATC-Zero routes for KCVG when ZID is ATC-Zero. Arrivals via BVT/ROD/OBK/DJB and departures via CVG SIDs to MIE/VHP/BVT/DJB/ROD.',
        'impacted_area' => 'ZID',
        'facilities_involved' => 'ZID,ZOB,ZTL,ZME',
    ],
    'ZID ATC-0 IND' => [
        'display_name' => 'ATC-Zero ZID - IND Routes (FCA009)',
        'description' => 'ATC-Zero routes for KIND when ZID is ATC-Zero. Arrivals via FWA/MZZ/SJAAY/ROD/PXV/BIB/USIRE and departures via IND SIDs to surrounding fixes.',
        'impacted_area' => 'ZID',
        'facilities_involved' => 'ZID,ZOB,ZAU,ZME',
    ],
    'ZID ATC-0 SDF' => [
        'display_name' => 'ATC-Zero ZID - SDF Routes (FCA004)',
        'description' => 'ATC-Zero routes for KSDF when ZID is ATC-Zero. Arrivals via DJB/ZARDA/PXV/RAMSE and departures via SARGO/APALO SIDs.',
        'impacted_area' => 'ZID',
        'facilities_involved' => 'ZID,ZOB,ZME,ZTL',
    ],
    'ZJX ATC-0' => [
        'display_name' => 'ATC-Zero ZJX - Routes (FCAZJX)',
        'description' => 'ATC-Zero routes when ZJX is ATC-Zero. Routes from HONID/ATL YUESS corridor to FL west coast airports (KTPA, KMCO, KAPF, KFMY, KMKY, KRSW) plus bypass segments.',
        'impacted_area' => 'ZJX',
        'facilities_involved' => 'ZJX,ZTL,ZMA',
    ],
    'ZLA ATC-0' => [
        'display_name' => 'ATC-Zero ZLA - Routes (FCAZLA)',
        'description' => 'ATC-Zero routes when ZLA is ATC-Zero. ZOA routing via MITEL PMD to KLAX, KLAS exit via ILC MLF.',
        'impacted_area' => 'ZLA',
        'facilities_involved' => 'ZLA,ZOA,ZLC',
    ],
    'ZMA ATC-0' => [
        'display_name' => 'ATC-Zero ZMA - Routes (FCAZMA)',
        'description' => 'ATC-Zero routes when ZMA is ATC-Zero. Northbound departures via WINCO JAYMC, southbound nonradar segments, tower enroute arrivals via OMN V3, and MAXIM/BORDO/ZEUSS overflights.',
        'impacted_area' => 'ZMA',
        'facilities_involved' => 'ZMA,ZJX,ZTL,ZHU',
    ],
    'ZME ATC-0 DEP' => [
        'display_name' => 'ATC-Zero ZME - Departure Routes (FCA004)',
        'description' => 'Departure routes from KMEM when ZME is ATC-Zero. Routes via MEM to ENL/FTZ/BYP/MCB/BNA/RMG jet routes.',
        'impacted_area' => 'ZME',
        'facilities_involved' => 'ZME,ZID,ZAU,ZHU,ZTL,ZFW',
    ],
    'ZME ATC-0 ARR' => [
        'display_name' => 'ATC-Zero ZME - Arrival Routes (FCA008)',
        'description' => 'Arrival routes to KMEM when ZME is ATC-Zero. Arrivals via VUZ/RYANS/ELD/SUTTN/TUL jet routes to MEM.',
        'impacted_area' => 'ZME',
        'facilities_involved' => 'ZME,ZID,ZFW,ZKC',
    ],
    'ZOB ATC-0 DEP' => [
        'display_name' => 'ATC-Zero ZOB - Departure Routes',
        'description' => 'Departure routes from KPIT/KCLE/KDTW area when ZOB is ATC-Zero. Routes via BSV/CAVVS/BARII SIDs to surrounding fixes.',
        'impacted_area' => 'ZOB',
        'facilities_involved' => 'ZOB,ZID,ZDC,ZNY',
    ],
    'ZOB ATC-0 ARR' => [
        'display_name' => 'ATC-Zero ZOB - Arrival Routes (FCA003)',
        'description' => 'Arrival routes to KPIT/KCLE/KDTW/KFDY/KPTK/KYIP when ZOB is ATC-Zero. Multiple connect fixes (APE, FWA, HEADZ, COLTZ, JOEBU) with FROM origins from all US ARTCCs.',
        'impacted_area' => 'ZOB',
        'facilities_involved' => 'ZOB,ZID,ZTL,ZJX,ZMA,ZME,ZFW,ZHU,ZKC,ZAB,ZLA,ZDV,ZDC,ZNY,ZBW,CZY,ZOA,ZSE,ZLC,ZMP,ZAU',
    ],
    'ZTL ATC-0 DEP' => [
        'display_name' => 'ATC-Zero ZTL - Departure Routes (FCA005)',
        'description' => 'Departure routes from KATL/KCLT when ZTL is ATC-Zero. KATL departures via BANNG2 SID, KCLT departures via LILLS2/KWEEN4/ICONS4/BEAVY5 SIDs.',
        'impacted_area' => 'ZTL',
        'facilities_involved' => 'ZTL,ZJX,ZDC,ZID',
    ],
    'ZTL ATC-0 ARR' => [
        'display_name' => 'ATC-Zero ZTL - Arrival Routes (FCA004)',
        'description' => 'Arrival routes to KATL/KCLT when ZTL is ATC-Zero. Multiple connect fixes (CEW, KAATT, HOTHH, OKNEE, COUPN, LYH, NUUMN) with FROM origins from all directions.',
        'impacted_area' => 'ZTL',
        'facilities_involved' => 'ZTL,ZMA,ZHU,ZME,ZFW,ZKC,ZDV,ZMP,ZAU,ZLC,ZSE,ZOA,ZLA,ZAB,ZJX,ZDC,ZNY,ZBW,ZID,ZOB',
    ],
];

// ============================================================================
// ROUTE NUMBER → PLAY MAPPING
// ============================================================================
$boundaries = [
    [1, 22, 'ZAB ATC-0 MEX'],
    [23, 182, 'ZDC ATC-0 FCA003'],
    [183, 191, 'ZDC ATC-0 FCA002'],
    [192, 195, 'ZDV ATC-0'],
    [196, 196, 'ZFW ATC-0'],
    [197, 201, 'ZHU ATC-0 DEP'],
    [202, 218, 'ZHU ATC-0 ARR'],
    [219, 230, 'ZHO ATC-0 GULF EB'],
    [231, 242, 'ZHO ATC-0 GULF WB'],
    [243, 255, 'ZID ATC-0 CVG'],
    [256, 276, 'ZID ATC-0 IND'],
    [277, 289, 'ZID ATC-0 SDF'],
    [290, 298, 'ZJX ATC-0'],
    [299, 300, 'ZLA ATC-0'],
    [301, 334, 'ZMA ATC-0'],
    [335, 340, 'ZME ATC-0 DEP'],
    [341, 345, 'ZME ATC-0 ARR'],
    [346, 353, 'ZOB ATC-0 DEP'],
    [354, 490, 'ZOB ATC-0 ARR'],
    [491, 497, 'ZTL ATC-0 DEP'],
    [498, 543, 'ZTL ATC-0 ARR'],
];

// ============================================================================
// ROUTE DATA (from ATC-Zero Avoidance Package, 543 routes)
// Format: route_num→route_string (comments start with ##)
// ============================================================================
$raw_routes = <<<'EOT'
1→ZOA MXL AMUDI IMEXA AGNID OBGIY THX LMEDA BELLR3 KHOU
2→ZLA MXL AMUDI IMEXA AGNID OBGIY THX LMEDA BELLR3 KHOU
3→ZOA MXL AMUDI IMEXA AGNID OBGIY THX YEEHA TEJAS4 KIAH
4→ZLA MXL AMUDI IMEXA AGNID OBGIY THX YEEHA TEJAS4 KIAH
5→ZOA MXL AMUDI IMEXA AGNID OBGIY THX PSX HOODO BOWFN LEV SJI J2 CEW JEFOI TEEEM Q109 PANDY BARTL J121 ORF J209 SBY J79 JFK ROBUC3 KBOS
6→ZLA MXL AMUDI IMEXA AGNID OBGIY THX PSX HOODO BOWFN LEV SJI J2 CEW JEFOI TEEEM Q109 PANDY BARTL J121 ORF J209 SBY J79 JFK ROBUC3 KBOS
7→ZOA MXL AMUDI IMEXA AGNID OBGIY THX PSX HOODO BOWFN LEV SJI J2 CEW JEFOI TEEEM Q99 POLYY TUBAS RDU GOOOB THHMP RAVNN6 KBWI
8→ZLA MXL AMUDI IMEXA AGNID OBGIY THX PSX HOODO BOWFN LEV SJI J2 CEW JEFOI TEEEM Q99 POLYY TUBAS RDU GOOOB THHMP RAVNN6 KBWI
9→ZOA MXL AMUDI IMEXA AGNID OBGIY THX PSX HOODO BOWFN LEV SJI J2 CEW JEFOI TEEEM Q99 POLYY TUBAS RDU FUUFF WAVES CAPSS3 KDCA
10→ZLA MXL AMUDI IMEXA AGNID OBGIY THX PSX HOODO BOWFN LEV SJI J2 CEW JEFOI TEEEM Q99 POLYY TUBAS RDU FUUFF WAVES CAPSS3 KDCA
11→ZOA MXL AMUDI IMEXA AGNID OBGIY THX PSX HOODO BOWFN LEV SJI J2 CEW JEFOI TEEEM Q99 POLYY TUBAS FOZZY FAK PHLBO3 KEWR
12→ZLA MXL AMUDI IMEXA AGNID OBGIY THX PSX HOODO BOWFN LEV SJI J2 CEW JEFOI TEEEM Q99 POLYY TUBAS FOZZY FAK PHLBO3 KEWR
13→ZOA MXL AMUDI IMEXA AGNID OBGIY THX PSX HOODO BOWFN LEV SJI J2 CEW JEFOI TEEEM Q99 POLYY TUBAS RDU BZNGA DORRN CAVLR3 KIAD
14→ZLA MXL AMUDI IMEXA AGNID OBGIY THX PSX HOODO BOWFN LEV SJI J2 CEW JEFOI TEEEM Q99 POLYY TUBAS RDU BZNGA DORRN CAVLR3 KIAD
15→ZOA MXL AMUDI IMEXA AGNID OBGIY THX PSX HOODO BOWFN LEV SJI J2 CEW JEFOI TEEEM Q109 PANDY BARTL J121 SIE CAMRN4 KJFK
16→ZLA MXL AMUDI IMEXA AGNID OBGIY THX PSX HOODO BOWFN LEV SJI J2 CEW JEFOI TEEEM Q109 PANDY BARTL J121 SIE CAMRN4 KJFK
17→ZOA MXL AMUDI IMEXA AGNID OBGIY THX PSX HOODO BOWFN LEV SJI J2 CEW JEFOI TEEEM Q99 POLYY TUBAS RDU ZITTO HPW J191 PXT KORRY4 KLGA
18→ZLA MXL AMUDI IMEXA AGNID OBGIY THX PSX HOODO BOWFN LEV SJI J2 CEW JEFOI TEEEM Q99 POLYY TUBAS RDU ZITTO HPW J191 PXT KORRY4 KLGA
19→ZOA MXL AMUDI IMEXA AGNID OBGIY THX PSX HOODO BOWFN LEV SJI J2 CEW JEFOI TEEEM Q99 POLYY TUBAS FOZZY FAK PAATS3 KPHL
20→ZLA MXL AMUDI IMEXA AGNID OBGIY THX PSX HOODO BOWFN LEV SJI J2 CEW JEFOI TEEEM Q99 POLYY TUBAS FOZZY FAK PAATS3 KPHL
21→ZOA MXL AMUDI IMEXA AGNID OBGIY THX PSX HOODO BOWFN LEV SJI J2 CEW JEFOI TEEEM Q99 POLYY TUBAS FOZZY FAK JAIKE3 KTEB
22→ZLA MXL AMUDI IMEXA AGNID OBGIY THX PSX HOODO BOWFN LEV SJI J2 CEW JEFOI TEEEM Q99 POLYY TUBAS FOZZY FAK JAIKE3 KTEB
23→ZTL SPA J83 APE JST MRB EMI KBWI
24→ZTL SPA J83 APE JST MRB EMI BELTS KDCA
25→ZTL SPA J83 APE JST MRB KIAD
26→ZTL SPA J83 APE JST BOJID2 KPHL
27→KAPF CAMJO TWINS SPA J83 APE JST MRB EMI KBWI
28→KFMY CAMJO TWINS SPA J83 APE JST MRB EMI KBWI
29→KMKY CAMJO TWINS SPA J83 APE JST MRB EMI KBWI
30→KPGD CAMJO TWINS SPA J83 APE JST MRB EMI KBWI
31→KPIE CAMJO TWINS SPA J83 APE JST MRB EMI KBWI
32→KRSW CAMJO TWINS SPA J83 APE JST MRB EMI KBWI
33→KSRQ CAMJO TWINS SPA J83 APE JST MRB EMI KBWI
34→KTPA CAMJO TWINS SPA J83 APE JST MRB EMI KBWI
35→KAPF CAMJO TWINS SPA J83 APE JST MRB EMI BELTS KDCA
36→KFMY CAMJO TWINS SPA J83 APE JST MRB EMI BELTS KDCA
37→KMKY CAMJO TWINS SPA J83 APE JST MRB EMI BELTS KDCA
38→KPGD CAMJO TWINS SPA J83 APE JST MRB EMI BELTS KDCA
39→KPIE CAMJO TWINS SPA J83 APE JST MRB EMI BELTS KDCA
40→KRSW CAMJO TWINS SPA J83 APE JST MRB EMI BELTS KDCA
41→KSRQ CAMJO TWINS SPA J83 APE JST MRB EMI BELTS KDCA
42→KTPA CAMJO TWINS SPA J83 APE JST MRB EMI BELTS KDCA
43→KAPF CAMJO TWINS SPA J83 APE JST MRB KIAD
44→KFMY CAMJO TWINS SPA J83 APE JST MRB KIAD
45→KMKY CAMJO TWINS SPA J83 APE JST MRB KIAD
46→KPGD CAMJO TWINS SPA J83 APE JST MRB KIAD
47→KPIE CAMJO TWINS SPA J83 APE JST MRB KIAD
48→KRSW CAMJO TWINS SPA J83 APE JST MRB KIAD
49→KSRQ CAMJO TWINS SPA J83 APE JST MRB KIAD
50→KTPA CAMJO TWINS SPA J83 APE JST MRB KIAD
51→KAPF CAMJO TWINS SPA J83 APE JST BOJID2 KPHL
52→KFMY CAMJO TWINS SPA J83 APE JST BOJID2 KPHL
53→KMKY CAMJO TWINS SPA J83 APE JST BOJID2 KPHL
54→KPGD CAMJO TWINS SPA J83 APE JST BOJID2 KPHL
55→KPIE CAMJO TWINS SPA J83 APE JST BOJID2 KPHL
56→KRSW CAMJO TWINS SPA J83 APE JST BOJID2 KPHL
57→KSRQ CAMJO TWINS SPA J83 APE JST BOJID2 KPHL
58→KTPA CAMJO TWINS SPA J83 APE JST BOJID2 KPHL
59→KATL RAFTN FLM J43 ROD APE JST MRB EMI KBWI
60→KATL RAFTN FLM J43 ROD APE JST MRB EMI BELTS KDCA
61→KATL RAFTN FLM J43 ROD APE JST MRB KIAD
62→KATL RAFTN FLM J43 ROD APE JST BOJID2 KPHL
63→KCLT CLAWD APE JST MRB EMI KBWI
64→KCLT CLAWD APE JST MRB EMI BELTS KDCA
65→KCLT CLAWD APE JST MRB KIAD
66→KCLT CLAWD APE JST BOJID2 KPHL
67→ZJX SHRKS Q77 WIGVO IRQ SPA J83 APE JST MRB EMI KBWI
68→ZJX SHRKS Q77 WIGVO IRQ SPA J83 APE JST MRB EMI BELTS KDCA
69→ZJX SHRKS Q77 WIGVO IRQ SPA J83 APE JST MRB KIAD
70→ZJX SHRKS Q77 WIGVO IRQ SPA J83 APE JST BOJID2 KPHL
71→ZMA WAKKO Q77 WIGVO IRQ SPA J83 APE JST MRB EMI KBWI
72→ZMA WAKKO Q77 WIGVO IRQ SPA J83 APE JST MRB EMI BELTS KDCA
73→ZMA WAKKO Q77 WIGVO IRQ SPA J83 APE JST MRB KIAD
74→ZMA WAKKO Q77 WIGVO IRQ SPA J83 APE JST BOJID2 KPHL
75→KAPF PATOY JOHNN Q118 ATL RAFTN FLM J43 ROD KLYNE Q29 DORET J584 SLT FQM3 KEWR
76→KMKY PATOY JOHNN Q118 ATL RAFTN FLM J43 ROD KLYNE Q29 DORET J584 SLT FQM3 KEWR
77→KATL RAFTN FLM J43 ROD KLYNE Q29 DORET J584 SLT FQM3 KEWR
78→KCLT DOOGE Q63 OCASE ROD KLYNE Q29 DORET J584 SLT FQM3 KEWR
79→KMCO BRUTS Q118 ATL RAFTN FLM J43 ROD KLYNE Q29 DORET J584 SLT FQM3 KEWR
80→KORL BRUTS Q118 ATL RAFTN FLM J43 ROD KLYNE Q29 DORET J584 SLT FQM3 KEWR
81→ZJX JOHNN Q118 ATL RAFTN FLM J43 ROD KLYNE Q29 DORET J584 SLT FQM3 KEWR
82→ZMA BRUTS Q118 ATL RAFTN FLM J43 ROD KLYNE Q29 DORET J584 SLT FQM3 KEWR
83→ZTL VXV J43 ROD KLYNE Q29 DORET J584 SLT FQM3 KEWR
84→KAPF PATOY JOHNN Q118 ATL RAFTN FLM J43 ROD KLYNE Q29 JHW J70 LVZ LENDY6 KJFK
85→KMKY PATOY JOHNN Q118 ATL RAFTN FLM J43 ROD KLYNE Q29 JHW J70 LVZ LENDY6 KJFK
86→KATL RAFTN FLM J43 ROD KLYNE Q29 JHW J70 LVZ LENDY6 KJFK
87→KCLT DOOGE Q63 OCASE ROD KLYNE Q29 JHW J70 LVZ LENDY6 KJFK
88→KMCO BRUTS Q118 ATL RAFTN FLM J43 ROD KLYNE Q29 JHW J70 LVZ LENDY6 KJFK
89→KORL BRUTS Q118 ATL RAFTN FLM J43 ROD KLYNE Q29 JHW J70 LVZ LENDY6 KJFK
90→ZJX JOHNN Q118 ATL RAFTN FLM J43 ROD KLYNE Q29 JHW J70 LVZ LENDY6 KJFK
91→ZMA BRUTS Q118 ATL RAFTN FLM J43 ROD KLYNE Q29 JHW J70 LVZ LENDY6 KJFK
92→ZTL VXV J43 ROD KLYNE Q29 JHW J70 LVZ LENDY6 KJFK
93→KAPF PATOY JOHNN Q118 ATL RAFTN FLM J43 ROD KLYNE Q29 WWSHR TEESY J146 ETG MIP4 KLGA
94→KMKY PATOY JOHNN Q118 ATL RAFTN FLM J43 ROD KLYNE Q29 WWSHR TEESY J146 ETG MIP4 KLGA
95→KATL RAFTN FLM J43 ROD KLYNE Q29 WWSHR TEESY J146 ETG MIP4 KLGA
96→KCLT DOOGE Q63 OCASE ROD KLYNE Q29 WWSHR TEESY J146 ETG MIP4 KLGA
97→KMCO BRUTS Q118 ATL RAFTN FLM J43 ROD KLYNE Q29 WWSHR TEESY J146 ETG MIP4 KLGA
98→KORL BRUTS Q118 ATL RAFTN FLM J43 ROD KLYNE Q29 WWSHR TEESY J146 ETG MIP4 KLGA
99→ZJX JOHNN Q118 ATL RAFTN FLM J43 ROD KLYNE Q29 WWSHR TEESY J146 ETG MIP4 KLGA
100→ZMA BRUTS Q118 ATL RAFTN FLM J43 ROD KLYNE Q29 WWSHR TEESY J146 ETG MIP4 KLGA
101→ZTL VXV J43 ROD KLYNE Q29 WWSHR TEESY J146 ETG MIP4 KLGA
102→KAPF PATOY JOHNN Q118 ATL RAFTN FLM J43 ROD KLYNE Q29 JHW LVZ4 KTEB
103→KMKY PATOY JOHNN Q118 ATL RAFTN FLM J43 ROD KLYNE Q29 JHW LVZ4 KTEB
104→KATL RAFTN FLM J43 ROD KLYNE Q29 JHW LVZ4 KTEB
105→KCLT DOOGE Q63 OCASE ROD KLYNE Q29 JHW LVZ4 KTEB
106→KMCO BRUTS Q118 ATL RAFTN FLM J43 ROD KLYNE Q29 JHW LVZ4 KTEB
107→KORL BRUTS Q118 ATL RAFTN FLM J43 ROD KLYNE Q29 JHW LVZ4 KTEB
108→ZJX JOHNN Q118 ATL RAFTN FLM J43 ROD KLYNE Q29 JHW LVZ4 KTEB
109→ZMA BRUTS Q118 ATL RAFTN FLM J43 ROD KLYNE Q29 JHW LVZ4 KTEB
110→ZTL VXV J43 ROD KLYNE Q29 JHW LVZ4 KTEB
111→KAUS FUZ TUL J87 JOT J146 WOOST J34 DJB JST MRB EMI KBWI
112→KSAT FUZ TUL J87 JOT J146 WOOST J34 DJB JST MRB EMI KBWI
113→KELP ADM TUL J87 JOT J146 WOOST J34 DJB JST MRB EMI KBWI
114→KIAH WTSON BYP TUL J87 JOT J146 WOOST J34 DJB JST MRB EMI KBWI
115→KHOU WTSON BYP TUL J87 JOT J146 WOOST J34 DJB JST MRB EMI KBWI
116→ZFW TUL J87 JOT J146 WOOST J34 DJB JST MRB EMI KBWI
117→ZHU TUL J87 JOT J146 WOOST J34 DJB JST MRB EMI KBWI
118→ZKC IRK J87 JOT J146 WOOST J34 DJB JST MRB EMI KBWI
119→ZME MEM STL J35 JOT J146 WOOST J34 DJB JST MRB EMI KBWI
120→KAUS FUZ TUL J87 JOT J146 WOOST J34 DJB JST MRB EMI BELTS KDCA
121→KSAT FUZ TUL J87 JOT J146 WOOST J34 DJB JST MRB EMI BELTS KDCA
122→KELP ADM TUL J87 JOT J146 WOOST J34 DJB JST MRB EMI BELTS KDCA
123→KIAH WTSON BYP TUL J87 JOT J146 WOOST J34 DJB JST MRB EMI BELTS KDCA
124→KHOU WTSON BYP TUL J87 JOT J146 WOOST J34 DJB JST MRB EMI BELTS KDCA
125→ZFW TUL J87 JOT J146 WOOST J34 DJB JST MRB EMI BELTS KDCA
126→ZHU TUL J87 JOT J146 WOOST J34 DJB JST MRB EMI BELTS KDCA
127→ZKC IRK J87 JOT J146 WOOST J34 DJB JST MRB EMI BELTS KDCA
128→ZME MEM STL J35 JOT J146 WOOST J34 DJB JST MRB EMI BELTS KDCA
129→KAUS FUZ TUL J87 JOT ELX CRL J584 SLT FQM3 KEWR
130→KSAT FUZ TUL J87 JOT ELX CRL J584 SLT FQM3 KEWR
131→KELP ADM TUL J87 JOT ELX CRL J584 SLT FQM3 KEWR
132→KIAH WTSON BYP TUL J87 JOT ELX CRL J584 SLT FQM3 KEWR
133→KHOU WTSON BYP TUL J87 JOT ELX CRL J584 SLT FQM3 KEWR
134→ZFW TUL J87 JOT ELX CRL J584 SLT FQM3 KEWR
135→ZHU TUL J87 JOT ELX CRL J584 SLT FQM3 KEWR
136→ZKC IRK J87 JOT ELX CRL J584 SLT FQM3 KEWR
137→ZME MEM STL J35 JOT ELX CRL J584 SLT FQM3 KEWR
138→KAUS FUZ TUL J87 JOT J146 WOOST J34 DJB JST MRB KIAD
139→KSAT FUZ TUL J87 JOT J146 WOOST J34 DJB JST MRB KIAD
140→KELP ADM TUL J87 JOT J146 WOOST J34 DJB JST MRB KIAD
141→KIAH WTSON BYP TUL J87 JOT J146 WOOST J34 DJB JST MRB KIAD
142→KHOU WTSON BYP TUL J87 JOT J146 WOOST J34 DJB JST MRB KIAD
143→ZFW TUL J87 JOT J146 WOOST J34 DJB JST MRB KIAD
144→ZHU TUL J87 JOT J146 WOOST J34 DJB JST MRB KIAD
145→ZKC IRK J87 JOT J146 WOOST J34 DJB JST MRB KIAD
146→ZME MEM STL J35 JOT J146 WOOST J34 DJB JST MRB KIAD
147→KAUS FUZ TUL J87 JOT ELX SVM J70 LVZ LENDY6 KJFK
148→KSAT FUZ TUL J87 JOT ELX SVM J70 LVZ LENDY6 KJFK
149→KELP ADM TUL J87 JOT ELX SVM J70 LVZ LENDY6 KJFK
150→KIAH WTSON BYP TUL J87 JOT ELX SVM J70 LVZ LENDY6 KJFK
151→KHOU WTSON BYP TUL J87 JOT ELX SVM J70 LVZ LENDY6 KJFK
152→ZFW TUL J87 JOT ELX SVM J70 LVZ LENDY6 KJFK
153→ZHU TUL J87 JOT ELX SVM J70 LVZ LENDY6 KJFK
154→ZKC IRK J87 JOT ELX SVM J70 LVZ LENDY6 KJFK
155→ZME MEM STL J35 JOT ELX SVM J70 LVZ LENDY6 KJFK
156→KAUS FUZ TUL J87 JOT J146 ETG MIP4 KLGA
157→KSAT FUZ TUL J87 JOT J146 ETG MIP4 KLGA
158→KELP ADM TUL J87 JOT J146 ETG MIP4 KLGA
159→KIAH WTSON BYP TUL J87 JOT J146 ETG MIP4 KLGA
160→KHOU WTSON BYP TUL J87 JOT J146 ETG MIP4 KLGA
161→ZFW TUL J87 JOT J146 ETG MIP4 KLGA
162→ZHU TUL J87 JOT J146 ETG MIP4 KLGA
163→ZKC IRK J87 JOT J146 ETG MIP4 KLGA
164→ZME MEM STL J35 JOT J146 ETG MIP4 KLGA
165→KAUS FUZ TUL J87 JOT J146 WOOST J34 DJB EWC JST BOJID2 KPHL
166→KSAT FUZ TUL J87 JOT J146 WOOST J34 DJB EWC JST BOJID2 KPHL
167→KELP ADM TUL J87 JOT J146 WOOST J34 DJB EWC JST BOJID2 KPHL
168→KIAH WTSON BYP TUL J87 JOT J146 WOOST J34 DJB EWC JST BOJID2 KPHL
169→KHOU WTSON BYP TUL J87 JOT J146 WOOST J34 DJB EWC JST BOJID2 KPHL
170→ZFW TUL J87 JOT J146 WOOST J34 DJB EWC JST BOJID2 KPHL
171→ZHU TUL J87 JOT J146 WOOST J34 DJB EWC JST BOJID2 KPHL
172→ZKC IRK J87 JOT J146 WOOST J34 DJB EWC JST BOJID2 KPHL
173→ZME MEM STL J35 JOT J146 WOOST J34 DJB EWC JST BOJID2 KPHL
174→KAUS FUZ TUL J87 JOT ELX SVM J70 JHW LVZ4 KTEB
175→KSAT FUZ TUL J87 JOT ELX SVM J70 JHW LVZ4 KTEB
176→KELP ADM TUL J87 JOT ELX SVM J70 JHW LVZ4 KTEB
177→KIAH WTSON BYP TUL J87 JOT ELX SVM J70 JHW LVZ4 KTEB
178→KHOU WTSON BYP TUL J87 JOT ELX SVM J70 JHW LVZ4 KTEB
179→ZFW TUL J87 JOT ELX SVM J70 JHW LVZ4 KTEB
180→ZHU TUL J87 JOT ELX SVM J70 JHW LVZ4 KTEB
181→ZKC IRK J87 JOT ELX SVM J70 JHW LVZ4 KTEB
182→ZME MEM STL J35 JOT ELX SVM J70 JHW LVZ4 KTEB
183→ZTL PSK V16 ROA V375 CLYFF CSN KIAD
184→ZTL PSK V16 ROA V375 CLYFF CSN KBWI
185→ZTL PSK V16 ROA V375 CLYFF CSN KDCA
186→ZMA ATL PSK V16 ROA V375 CLYFF CSN KIAD
187→ZJX ATL PSK V16 ROA V375 CLYFF CSN KIAD
188→ZMA ATL PSK V16 ROA V375 CLYFF CSN KBWI
189→ZJX ATL PSK V16 ROA V375 CLYFF CSN KBWI
190→ZMA ATL PSK V16 ROA V375 CLYFF CSN KDCA
191→ZJX ATL PSK V16 ROA V375 CLYFF CSN KDCA
192→UNKN PGS INW CIM LBL ICT UNKN
193→UNKN ABR BIL DBS UNKN
194→UNKN PGS BCE OCS BOY UNKN
195→UNKN RWF LMN BUM ICT UNKN
196→UNKN MARTA KSHV
197→KIAH IAH CRIED BEREE1 KDFW
198→KHOU IAH CRIED REDDN REDDN4 KDAL
199→KIAH LOA WTSON CVE UNKN
200→KSAT SAT V550 PINCH ELOEL UNKN
201→KAUS WLMRT ELOEL2 ABI UNKN
202→UNKN CVE RIICE8 KIAH
203→UNKN INK CVE RIICE8 KIAH
204→UNKN MGM SQS CVE RIICE8 KIAH
205→KSAT SAT V550 CWK V306 ILEXY RIICE8 KIAH
206→UNKN CVE TORNN HOMRN RIICE HOU KHOU
207→UNKN INK CVE TORNN HOMRN RIICE HOU KHOU
208→UNKN MGM SQS CVE TORNN HOMRN RIICE HOU KHOU
209→KSAT SAT V550 CWK V306 ILEXY RIICE HOU KHOU
210→UNKN ACT WINDU BRAUN3 KSAT
211→UNKN ACT WINDU MARCS1 KSAT
212→UNKN INK CVE ACT WINDU BRAUN3 KSAT
213→UNKN INK CVE ACT WINDU MARCS1 KSAT
214→UNKN MGM SQS CVE ACT WINDU BRAUN3 KSAT
215→UNKN MGM SQS CVE ACT WINDU MARCS1 KSAT
216→UNKN INK CVE WINDU SEWZY4 KAUS
217→UNKN MGM SQS CVE WINDU SEWZY4 KAUS
218→UNKN WINDU SEWZY4 KAUS
219→UNKN LAMMY KENGS REMIS ZMA
220→UNKN LAMMY KENGS REMIS KMCO
221→UNKN LAMMY KENGS BACCA ZMA
222→UNKN LAMMY KENGS BACCA KMCO
223→KDFW BILEE IAH KENGS REMIS ZMA
224→KDFW BILEE IAH KENGS REMIS KMCO
225→KDAL BILEE IAH KENGS REMIS ZMA
226→KDAL BILEE IAH KENGS REMIS KMCO
227→KDFW BILEE IAH KENGS BACCA ZMA
228→KDFW BILEE IAH KENGS BACCA KMCO
229→KDAL BILEE IAH KENGS BACCA ZMA
230→KDAL BILEE IAH KENGS BACCA KMCO
231→ZMA REMIS KENGS IAH BILEE UNKN
232→KMCO REMIS KENGS IAH BILEE UNKN
233→ZMA BACCA KENGS IAH BILEE UNKN
234→KMCO BACCA KENGS IAH BILEE UNKN
235→ZMA REMIS KENGS IAH CRIED BEREE1 KDFW
236→KMCO REMIS KENGS IAH CRIED BEREE1 KDFW
237→ZMA BACCA KENGS IAH CRIED BEREE1 KDFW
238→KMCO BACCA KENGS IAH CRIED BEREE1 KDFW
239→ZMA REMIS KENGS IAH MAJKK REDDN4 KDAL
240→KMCO REMIS KENGS IAH MAJKK REDDN4 KDAL
241→ZMA BACCA KENGS IAH MAJKK REDDN4 KDAL
242→KMCO BACCA KENGS IAH MAJKK REDDN4 KDAL
243→UNKN BVT CEGRM5 KCVG
244→UNKN ROD CINCE9 KCVG
245→UNKN OBK SHB6 KCVG
246→UNKN DJB ROD CINCE9 KCVG
247→UNKN DJB APE TIGRR2 KCVG
248→KCVG CVG CVG5 MIE UNKN
249→KCVG CVG JBNCH5 MIE UNKN
250→KCVG CVG WHWTR9 VHP UNKN
251→KCVG CVG LOVEY6 BVT UNKN
252→KCVG CVG CVG5 DQN RIKLE DJB UNKN
253→KCVG CVG BNGLE4 DJB UNKN
254→KCVG CVG HAGOL4 ROD UNKN
255→KCVG CVG ROCKT1 ROCKT ARRAY APE DJB UNKN
256→UNKN FWA CLANG7 KIND
257→UNKN MZZ CLANG7 KIND
258→UNKN SJAAY SNKPT2 KIND
259→UNKN ROD CLANG7 KIND
260→UNKN RINTE SNKPT2 KIND
261→UNKN PXV RACYR5 KIND
262→UNKN BIB RACYR5 KIND
263→UNKN USIRE KOLTS2 KIND
264→KIND IND INDY9 VHP UNKN
265→KIND IND INDY9 OKK UNKN
266→KIND IND INDY9 MZZ UNKN
267→KIND IND MEARZ6 BVT UNKN
268→KIND IND MEARZ6 OKK UNKN
269→KIND IND MEARZ6 MZZ UNKN
270→KIND IND MAREO5 VHP UNKN
271→KIND IND MAREO5 MIE UNKN
272→KIND IND INDY9 ROD UNKN
273→KIND IND MAREO5 ROD UNKN
274→KIND OOM PXV BNA UNKN
275→KIND IND ROCKY1 STL UNKN
276→KIND IND ROCKY1 SPI UNKN
277→UNKN DJB CVG RDSTN6 KSDF
278→UNKN DJB ROD RDSTN6 KSDF
279→UNKN DJB APE RDSTN6 KSDF
280→UNKN DJB CVG DLAMP6 KSDF
281→UNKN DJB UKATS CVG DLAMP6 KSDF
282→UNKN MALDN CVG DLAMP6 KSDF
283→UNKN DJB UKATS DLAMP6 KSDF
284→UNKN ZARDA CHERI4 KSDF
285→UNKN PXV CHERI4 KSDF
286→UNKN RAMSE FRIZN FRIZN5 KSDF
287→KSDF SARGO BATHY ROD KLYNE UNKN
288→KSDF SDF APALO6 APALO BNA UNKN
289→KSDF SDF APALO6 APALO UNKN
290→UNKN HONID Q81 BULZI HEVVN BLOND BLOND5 KTPA
291→UNKN HONID Q81 BULZI HEVVN Q104 PIE COSTR3 KMCO
292→UNKN DBN V267 CRG UNKN
293→UNKN ATL YUESS Q79 DOFFY Q79 MOLIE UNKN
294→UNKN ATL YUESS Q79 DOFFY Q79 MOLIE PIKKR PIKKR5 KAPF
295→UNKN ATL YUESS Q79 DOFFY Q79 MOLIE FRZBE TYNEE2 KFMY
296→UNKN WAKKO Q77 TEUFL WIGVO UNKN
297→UNKN ATL YUESS Q79 DOFFY Q79 MOLIE PIKKR PIKKR5 KMKY
298→UNKN ATL YUESS Q79 DOFFY Q79 MOLIE FRZBE TYNEE2 KRSW
299→ZOA MITEL PMD LAX KLAX
300→KLAS ILC MLF UNKN
301→KMIA WINCO JAYMC Q110 SHEEK SMELZ UNKN
302→KTMB WINCO JAYMC Q110 SHEEK SMELZ UNKN
303→KOPF WINCO JAYMC Q110 SHEEK SMELZ UNKN
304→KFLL WINCO JAYMC Q110 SHEEK SMELZ UNKN
305→KFXE WINCO JAYMC Q110 SHEEK SMELZ UNKN
306→UNKN GRATX B646 ZQA R628 UVA UNKN
307→UNKN BAHA AR17 VKZ G430 EONNS A509 URSUS UNKN
308→UNKN MOLIE Q79 VAULT MTH B646 CANOA UNKN
309→KMIA EONNS A509 URSUS UNKN
310→KTMB EONNS A509 URSUS UNKN
311→KOPF EONNS A509 URSUS UNKN
312→KFLL EONNS A509 URSUS UNKN
313→KFXE EONNS A509 URSUS UNKN
314→KMIA MIA MNATE Y442 FUNDI UNKN
315→KTMB MIA MNATE Y442 FUNDI UNKN
316→KOPF MIA MNATE Y442 FUNDI UNKN
317→KFLL MIA MNATE Y442 FUNDI UNKN
318→KFXE MIA MNATE Y442 FUNDI UNKN
319→UNKN ZEUSS Y217 OCTAL Q77 MATLK Q87 ZERBO UNKN
320→UNKN MAXIM Y262 TUNSL FEMID Q118 JINOS UNKN
321→UNKN OMN V3 TRV PBI KPBI
322→UNKN OMN V3 PBI MIA KMIA
323→UNKN OMN V3 PBI FLL KFLL
324→UNKN OMN V3 PBI OPF KOPF
325→UNKN OMN V3 PBI TMB KTMB
326→UNKN OMN V3 PBI FXE KFXE
327→UNKN MAXIM G765 FIS EYW DVALL FAMIN KMIA
328→UNKN MAXIM G765 FIS EYW DVALL FAMIN KOPF
329→UNKN MAXIM G765 FIS EYW DVALL FAMIN KFLL
330→UNKN MAXIM G765 FIS EYW DVALL FAMIN KTMB
331→UNKN MAXIM G765 FIS EYW DVALL FAMIN KFXE
332→UNKN BORDO ZBV DEKAL5 KFLL
333→UNKN BORDO ZBV DEKAL5 KFXE
334→UNKN ZEUSS FOWEE FLIPR7 KMIA
335→KMEM MEM J71 ENL UNKN
336→KMEM MEM J187 FTZ UNKN
337→KMEM MEM J66 BYP UNKN
338→KMEM MEM J35 MCB UNKN
339→KMEM MEM J42 BNA GHATS UNKN
340→KMEM MEM J66 RMG UNKN
341→UNKN VUZ J41 MEM KMEM
342→UNKN RYANS J6 BWG 3544N/8929W MEM KMEM
343→UNKN ELD J29 MEM KMEM
344→UNKN SUTTN J29 MEM KMEM
345→UNKN TUL J46 ARG V159 GQE KMEM
346→KPIT BSV MFD FBC OLK UNKN
347→KPIT BSV DQN UNKN
348→KCLE CLE CAVVS4 CAVVS APE UNKN
349→KCLE CLE GTLKE4 AYYLE BRNIN ELEOT YABRO UNKN
350→KDTW DTW BARII2 SINKR UNKN
351→KYIP DTW BARII2 SINKR UNKN
352→KPTK DTW BARII2 SINKR UNKN
353→KFDY BARII SINKR UNKN
354→ZID APE KFDY
355→ZTL APE KFDY
356→ZJX APE KFDY
357→ZMA APE KFDY
358→ZME APE KFDY
359→ZFW APE KFDY
360→ZHU APE KFDY
361→ZKC APE KFDY
362→ZAB APE KFDY
363→ZLA APE KFDY
364→ZDV APE KFDY
365→ZDC HNN APE KFDY
366→ZNY MRB HNN APE KFDY
367→ZBW MRB HNN APE KFDY
368→CZY BUF ELM MRB HNN APE KFDY
369→ZID APE BSV JESEY4 KPIT
370→ZTL APE BSV JESEY4 KPIT
371→ZJX APE BSV JESEY4 KPIT
372→ZMA APE BSV JESEY4 KPIT
373→ZME APE BSV JESEY4 KPIT
374→ZFW APE BSV JESEY4 KPIT
375→ZHU APE BSV JESEY4 KPIT
376→ZKC APE BSV JESEY4 KPIT
377→ZAB APE BSV JESEY4 KPIT
378→ZLA APE BSV JESEY4 KPIT
379→ZDV APE BSV JESEY4 KPIT
380→ZDC HNN APE BSV JESEY4 KPIT
381→ZNY MRB HNN APE BSV JESEY4 KPIT
382→ZBW MRB HNN APE BSV JESEY4 KPIT
383→CZY BUF ELM MRB HNN APE BSV JESEY4 KPIT
384→ZKC FWA ROKNN ROKNN3 KCLE
385→ZLA FWA ROKNN ROKNN3 KCLE
386→ZOA FWA ROKNN ROKNN3 KCLE
387→ZSE FWA ROKNN ROKNN3 KCLE
388→ZLC FWA ROKNN ROKNN3 KCLE
389→ZMP FWA ROKNN ROKNN3 KCLE
390→ZAU FWA ROKNN ROKNN3 KCLE
391→ZDV FWA ROKNN ROKNN3 KCLE
392→ZKC FWA KFDY
393→ZLA FWA KFDY
394→ZOA FWA KFDY
395→ZSE FWA KFDY
396→ZLC FWA KFDY
397→ZMP FWA KFDY
398→ZAU FWA KFDY
399→ZDV FWA KFDY
400→ZKC FWA BSV JESEY4 KPIT
401→ZLA FWA BSV JESEY4 KPIT
402→ZOA FWA BSV JESEY4 KPIT
403→ZSE FWA BSV JESEY4 KPIT
404→ZLC FWA BSV JESEY4 KPIT
405→ZMP FWA BSV JESEY4 KPIT
406→ZAU FWA BSV JESEY4 KPIT
407→ZDV FWA BSV JESEY4 KPIT
408→ZID HEADZ ROKNN3 KCLE
409→ZTL HEADZ ROKNN3 KCLE
410→ZJX HEADZ ROKNN3 KCLE
411→ZMA HEADZ ROKNN3 KCLE
412→ZME HEADZ ROKNN3 KCLE
413→ZFW HEADZ ROKNN3 KCLE
414→ZHU HEADZ ROKNN3 KCLE
415→ZKC HEADZ ROKNN3 KCLE
416→ZAB HEADZ ROKNN3 KCLE
417→ZLA HEADZ ROKNN3 KCLE
418→ZDV HEADZ ROKNN3 KCLE
419→ZDC HNN HEADZ ROKNN3 KCLE
420→ZNY MRB HNN HEADZ ROKNN3 KCLE
421→ZBW MRB HNN HEADZ ROKNN3 KCLE
422→ZDC HNN SUBWY COLTZ CRAKN2 KDTW
423→ZID SUBWY COLTZ CRAKN2 KDTW
424→ZTL SUBWY COLTZ CRAKN2 KDTW
425→ZJX SUBWY COLTZ CRAKN2 KDTW
426→ZMA SUBWY COLTZ CRAKN2 KDTW
427→ZME SUBWY COLTZ CRAKN2 KDTW
428→ZFW SUBWY COLTZ CRAKN2 KDTW
429→ZHU SUBWY COLTZ CRAKN2 KDTW
430→ZKC SUBWY COLTZ CRAKN2 KDTW
431→ZAB SUBWY COLTZ CRAKN2 KDTW
432→ZLA SUBWY COLTZ CRAKN2 KDTW
433→ZDV SUBWY COLTZ CRAKN2 KDTW
434→ZNY MRB HNN COLTZ CRAKN2 KDTW
435→ZBW MRB HNN COLTZ CRAKN2 KDTW
436→CZY BUF ELM MRB HNN COLTZ CRAKN2 KDTW
437→ZDC HNN SUBWY COLTZ KPTK
438→ZID SUBWY COLTZ KPTK
439→ZTL SUBWY COLTZ KPTK
440→ZJX SUBWY COLTZ KPTK
441→ZMA SUBWY COLTZ KPTK
442→ZME SUBWY COLTZ KPTK
443→ZFW SUBWY COLTZ KPTK
444→ZHU SUBWY COLTZ KPTK
445→ZKC SUBWY COLTZ KPTK
446→ZAB SUBWY COLTZ KPTK
447→ZLA SUBWY COLTZ KPTK
448→ZDV SUBWY COLTZ KPTK
449→ZNY MRB HNN COLTZ KPTK
450→ZBW MRB HNN COLTZ KPTK
451→CZY BUF ELM MRB HNN COLTZ KPTK
452→ZDC HNN SUBWY COLTZ KYIP
453→ZID SUBWY COLTZ KYIP
454→ZTL SUBWY COLTZ KYIP
455→ZJX SUBWY COLTZ KYIP
456→ZMA SUBWY COLTZ KYIP
457→ZME SUBWY COLTZ KYIP
458→ZFW SUBWY COLTZ KYIP
459→ZHU SUBWY COLTZ KYIP
460→ZKC SUBWY COLTZ KYIP
461→ZAB SUBWY COLTZ KYIP
462→ZLA SUBWY COLTZ KYIP
463→ZDV SUBWY COLTZ KYIP
464→ZNY MRB HNN COLTZ KYIP
465→ZBW MRB HNN COLTZ KYIP
466→CZY BUF ELM MRB HNN COLTZ KYIP
467→ZKC JOEBU LECTR3 KDTW
468→ZLA JOEBU LECTR3 KDTW
469→ZOA JOEBU LECTR3 KDTW
470→ZSE JOEBU LECTR3 KDTW
471→ZLC JOEBU LECTR3 KDTW
472→ZMP JOEBU LECTR3 KDTW
473→ZAU JOEBU LECTR3 KDTW
474→ZDV JOEBU LECTR3 KDTW
475→ZKC JOEBU KPTK
476→ZLA JOEBU KPTK
477→ZOA JOEBU KPTK
478→ZSE JOEBU KPTK
479→ZLC JOEBU KPTK
480→ZMP JOEBU KPTK
481→ZAU JOEBU KPTK
482→ZDV JOEBU KPTK
483→ZKC JOEBU KYIP
484→ZLA JOEBU KYIP
485→ZOA JOEBU KYIP
486→ZSE JOEBU KYIP
487→ZLC JOEBU KYIP
488→ZMP JOEBU KYIP
489→ZAU JOEBU KYIP
490→ZDV JOEBU KYIP
491→KATL ATL BANNG2 LUCKK HONID CEW UNKN
492→KATL ATL BANNG2 LUCKK HONID OTK RDU UNKN
493→KCLT CLT LILLS2 LILLS UNKN
494→KCLT CLT KWEEN4 PITRW UNKN
495→KCLT CLT ICONS4 NOOKS UNKN
496→KCLT CLT BEAVY5 JENDO UNKN
497→KCLT CLT BEAVY5 GANDT UNKN
498→ZMA LAL CEW ENNTT HOBTT2 KATL
499→ZHU GCV CEW ENNTT HOBTT2 KATL
500→ZME MHZ GCV CEW ENNTT HOBTT2 KATL
501→ZFW MCB GCV CEW ENNTT HOBTT2 KATL
502→KMCI MHZ GCV CEW ENNTT HOBTT2 KATL
503→KSTL MHZ GCV CEW ENNTT HOBTT2 KATL
504→KSGF MHZ GCV CEW ENNTT HOBTT2 KATL
505→ZKC CVE MCB GCV CEW ENNTT HOBTT2 KATL
506→ZDV MMB CVE MCB GCV CEW ENNTT HOBTT2 KATL
507→ZMP SGF MHZ GCV CEW ENNTT HOBTT2 KATL
508→ZAU FAM MHZ GCV CEW ENNTT HOBTT2 KATL
509→ZLC FQF MMB CVE MCB GCV CEW ENNTT HOBTT2 KATL
510→ZSE FQF MMB CVE MCB GCV CEW ENNTT HOBTT2 KATL
511→ZOA FQF MMB CVE MCB GCV CEW ENNTT HOBTT2 KATL
512→ZLA CVE MCB GCV CEW ENNTT HOBTT2 KATL
513→ZAB CVE MCB GCV CEW ENNTT HOBTT2 KATL
514→ZMA LAL CEW SZW OKNEE MLLET2 KCLT
515→ZHU GCV CEW SZW OKNEE MLLET2 KCLT
516→ZME MHZ GCV CEW SZW OKNEE MLLET2 KCLT
517→ZFW MCB GCV CEW SZW OKNEE MLLET2 KCLT
518→KMCI MHZ GCV CEW SZW OKNEE MLLET2 KCLT
519→KSTL MHZ GCV CEW SZW OKNEE MLLET2 KCLT
520→KSGF MHZ GCV CEW SZW OKNEE MLLET2 KCLT
521→ZKC CVE MCB GCV CEW SZW OKNEE MLLET2 KCLT
522→ZDV MMB CVE MCB GCV CEW SZW OKNEE MLLET2 KCLT
523→ZMP SGF MHZ GCV CEW SZW OKNEE MLLET2 KCLT
524→ZAU FAM MHZ GCV CEW SZW OKNEE MLLET2 KCLT
525→ZLC FQF MMB CVE MCB GCV CEW SZW OKNEE MLLET2 KCLT
526→ZSE FQF MMB CVE MCB GCV CEW SZW OKNEE MLLET2 KCLT
527→ZOA FQF MMB CVE MCB GCV CEW SZW OKNEE MLLET2 KCLT
528→ZLA CVE MCB GCV CEW SZW OKNEE MLLET2 KCLT
529→ZAB CVE MCB GCV CEW SZW OKNEE MLLET2 KCLT
530→ZDC KAATT HOTHH JJEDI2 KATL
531→ZNY ORF KAATT HOTHH JJEDI2 KATL
532→ZBW ORF KAATT HOTHH JJEDI2 KATL
533→ZID ROA RDU KAATT HOTHH JJEDI2 KATL
534→ZOB ROA RDU KAATT HOTHH JJEDI2 KATL
535→ZJX HOTHH JJEDI2 KATL
536→KILM OKNEE MLLET2 KCLT
537→ZJX OKNEE MLLET2 KCLT
538→ZMA CEW SZW OKNEE MLLET2 KCLT
539→ZID LYH CHSLY4 KCLT
540→ZOB LYH CHSLY4 KCLT
541→ZNY ORF COUPN CHSLY4 KCLT
542→ZBW ORF COUPN CHSLY4 KCLT
543→ZDC NUUMN CHSLY4 KCLT
EOT;

// ============================================================================
// PARSE ROUTE DATA
// ============================================================================
$parsed_routes = [];
foreach (explode("\n", $raw_routes) as $line) {
    $line = trim($line);
    if (!$line) continue;
    if (!preg_match('/^(\d+)\x{2192}(.+)$/u', $line, $m)) continue;

    $num = (int)$m[1];
    $route_str = trim($m[2]);

    $play_key = null;
    foreach ($boundaries as [$start, $end, $key]) {
        if ($num >= $start && $num <= $end) {
            $play_key = $key;
            break;
        }
    }
    if (!$play_key) {
        echo "WARNING: Route #$num has no play mapping, skipping\n";
        continue;
    }

    [$origin, $dest, $orig_apt, $orig_artcc, $dest_apt, $dest_artcc] = parseOriginDest($route_str);

    $parsed_routes[] = [
        'play'        => $play_key,
        'route'       => $route_str,
        'origin'      => $origin,
        'dest'        => $dest,
        'orig_apt'    => $orig_apt,
        'orig_artcc'  => $orig_artcc,
        'dest_apt'    => $dest_apt,
        'dest_artcc'  => $dest_artcc,
    ];
}

$total_routes = count($parsed_routes);
$play_count = count($plays);
echo "ATC-Zero Import: $play_count plays, $total_routes routes parsed\n";
flush();

if ($total_routes !== 543) {
    echo "WARNING: Expected 543 routes, got $total_routes\n";
}

// ============================================================================
// CHECK FOR EXISTING DATA
// ============================================================================

// Check existing ATC_ZERO plays (our namespace)
$existing_atz = (int)$pdo->query("SELECT COUNT(*) FROM playbook_plays WHERE source='DCC' AND org_code='ATC_ZERO'")->fetchColumn();
$is_reimport = $existing_atz > 0;
echo $is_reimport ? "Re-import ($existing_atz existing ATC_ZERO plays will be replaced)\n" : "First import\n";

// Build set of existing Contingency route strings (from OTHER sources, not ATC_ZERO)
$existing_routes = [];
$stmt = $pdo->query("
    SELECT r.route_string
    FROM playbook_routes r
    JOIN playbook_plays p ON r.play_id = p.play_id
    WHERE p.category = 'Contingency'
      AND NOT (p.source = 'DCC' AND p.org_code = 'ATC_ZERO')
");
while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
    $existing_routes[strtoupper(trim($row['route_string']))] = true;
}
$existing_count = count($existing_routes);
echo "Found $existing_count existing Contingency routes (from other sources)\n";
flush();

// ============================================================================
// IMPORT EXECUTION
// ============================================================================
$pdo->beginTransaction();

try {
    // Delete existing ATC_ZERO data (idempotent reimport)
    if ($is_reimport) {
        $pdo->exec("DELETE FROM playbook_changelog WHERE play_id IN (SELECT play_id FROM playbook_plays WHERE source='DCC' AND org_code='ATC_ZERO')");
        $pdo->exec("DELETE FROM playbook_plays WHERE source='DCC' AND org_code='ATC_ZERO'");
        echo "Deleted existing ATC_ZERO data\n";
        flush();
    }

    // Filter out routes that already exist in other Contingency plays
    $new_routes = [];
    $skipped = 0;
    foreach ($parsed_routes as $r) {
        $key = strtoupper(trim($r['route']));
        if (isset($existing_routes[$key])) {
            $skipped++;
        } else {
            $new_routes[] = $r;
        }
    }
    echo "Skipping $skipped routes already in existing Contingency plays\n";
    echo "Inserting " . count($new_routes) . " new routes\n";
    flush();

    // Count routes per play (for new routes only)
    $play_route_counts = [];
    foreach ($new_routes as $r) {
        $play_route_counts[$r['play']] = ($play_route_counts[$r['play']] ?? 0) + 1;
    }

    // Insert plays (only those that have at least one new route)
    $play_ids = [];
    $plays_inserted = 0;
    $play_stmt = $pdo->prepare("INSERT INTO playbook_plays
        (play_name, play_name_norm, display_name, description, category,
         impacted_area, facilities_involved, route_format,
         source, status, route_count, org_code, created_by, created_at)
        VALUES (?,?,?,?,?,?,?,'standard','DCC','active',?,'ATC_ZERO','import',NOW())");

    foreach ($plays as $pn => $pd) {
        $rc = $play_route_counts[$pn] ?? 0;
        if ($rc === 0) {
            echo "  Skipping play '$pn' (all routes already exist)\n";
            continue;
        }

        $play_stmt->execute([
            $pn,
            normPlay($pn),
            $pd['display_name'],
            $pd['description'],
            'Contingency',
            $pd['impacted_area'],
            $pd['facilities_involved'],
            $rc,
        ]);
        $play_ids[$pn] = (int)$pdo->lastInsertId();
        $plays_inserted++;
    }
    echo "Inserted $plays_inserted plays\n";
    flush();

    // Insert routes in batches
    $route_batch = [];
    $sort_counters = [];
    $routes_inserted = 0;

    foreach ($new_routes as $r) {
        $pn = $r['play'];
        $pid = $play_ids[$pn] ?? null;
        if (!$pid) continue;

        if (!isset($sort_counters[$pn])) $sort_counters[$pn] = 0;

        $route_batch[] = [
            $pid, $r['route'], $r['origin'], $r['dest'],
            $r['orig_apt'], $r['orig_artcc'],
            $r['dest_apt'], $r['dest_artcc'],
            $sort_counters[$pn]++
        ];

        if (count($route_batch) >= 100) {
            $vals = [];
            $params = [];
            foreach ($route_batch as $rb) {
                $vals[] = "(?,?,?,?,?,?,?,?,?)";
                $params = array_merge($params, $rb);
            }
            $pdo->prepare("INSERT INTO playbook_routes (play_id, route_string, origin, dest, origin_airports, origin_artccs, dest_airports, dest_artccs, sort_order) VALUES " . implode(',', $vals))->execute($params);
            $routes_inserted += count($route_batch);
            $route_batch = [];
        }
    }

    // Flush remaining
    if (count($route_batch) > 0) {
        $vals = [];
        $params = [];
        foreach ($route_batch as $rb) {
            $vals[] = "(?,?,?,?,?,?,?,?,?)";
            $params = array_merge($params, $rb);
        }
        $pdo->prepare("INSERT INTO playbook_routes (play_id, route_string, origin, dest, origin_airports, origin_artccs, dest_airports, dest_artccs, sort_order) VALUES " . implode(',', $vals))->execute($params);
        $routes_inserted += count($route_batch);
    }

    echo "Inserted $routes_inserted routes\n";
    flush();

    // Changelog entries
    $action = $is_reimport ? 'faa_reimport' : 'faa_import';
    if (!empty($play_ids)) {
        $cl_vals = [];
        $cl_params = [];
        foreach ($play_ids as $pn => $pid) {
            $cl_vals[] = "(?,'$action','import',NOW())";
            $cl_params[] = $pid;
        }
        $pdo->prepare("INSERT INTO playbook_changelog (play_id, action, changed_by, changed_at) VALUES " . implode(',', $cl_vals))->execute($cl_params);
    }

    $pdo->commit();
    echo "\nDone: $plays_inserted plays, $routes_inserted routes, $skipped skipped (already existed)\n";

    // Verify
    $verify = $pdo->query("SELECT COUNT(*) AS plays FROM playbook_plays WHERE source='DCC' AND org_code='ATC_ZERO'")->fetch();
    $verify_r = $pdo->query("SELECT COUNT(*) AS routes FROM playbook_routes WHERE play_id IN (SELECT play_id FROM playbook_plays WHERE source='DCC' AND org_code='ATC_ZERO')")->fetch();
    echo "Verify: {$verify['plays']} plays, {$verify_r['routes']} routes in DB\n";

    // Show per-play breakdown
    echo "\nPer-play breakdown:\n";
    $breakdown = $pdo->query("
        SELECT p.play_name, p.route_count,
               (SELECT COUNT(*) FROM playbook_routes r WHERE r.play_id = p.play_id) AS actual_routes
        FROM playbook_plays p
        WHERE p.source = 'DCC' AND p.org_code = 'ATC_ZERO'
        ORDER BY p.play_id
    ");
    while ($row = $breakdown->fetch(PDO::FETCH_ASSOC)) {
        echo "  {$row['play_name']}: {$row['actual_routes']} routes\n";
    }

} catch (Exception $e) {
    $pdo->rollBack();
    echo "FAILED (rolled back): " . $e->getMessage() . "\n";
}
